app = "antiqueclocks"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  # WORDPRESS_DB_HOST = ""
  # WORDPRESS_DB_USER = ""
  # WORDPRESS_DB_PASSWORD = ""
  # WORDPRESS_DB_NAME = ""
  WORDPRESS_MYSQL_SSL=1
  # WORDPRESS_AUTH_KEY= ""
  # WORDPRESS_SECURE_AUTH_KEY= ""
  # WORDPRESS_LOGGED_IN_KEY= ""
  # WORDPRESS_NONCE_KEY= ""
  # WORDPRESS_AUTH_SALT= ""
  # WORDPRESS_SECURE_AUTH_SALT= ""
  # WORDPRESS_LOGGED_IN_SALT= ""
  # WORDPRESS_NONCE_SALT = ""
  
[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
