version: '3.8'

services: 
  wordpress:
    # Overrides default command so things don't shut down after the process ends.
    command: start-dev-env
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    restart: unless-stopped
    ports:
      - "8085:8080"
      - "3306:3306"
      - "8443:8443"
    # Add "forwardPorts": ["3306"] to **devcontainer.json** to forward MariaDB locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
  
